var simplemaps_usmap_mapdata = {
  main_settings: {
    //General settings
    width: "responsive", //'700' or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    popups: "detect",

    //State defaults
    state_description: "", //"State Description",
    state_color: "#b167d3",
    state_hover_color: "#d4aae7",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "yes",
    all_states_zoomable: "no",

    //Location defaults
    location_description: "Add location markers using latitude and longitude!",
    location_color: "#2041D4",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_url: "",
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    //Label defaults
    label_color: "#d5ddec",
    label_hover_color: "#d5ddec",
    label_size: 22,
    label_font: "europa",
    hide_labels: "no",
    hide_eastern_labels: "no",
    manual_zoom: "no",
    back_image: "no",
    initial_back: "no",
    initial_zoom: -1,
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    //Popup settings
    popup_color: "white",
    popup_opacity: 1,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "europa",
    popup_nocss: "no",

    //Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "yes",
    images_directory: "/static/lib/simplemaps/map_images/",
    fade_time: 0.1,
    import_labels: "no",
    link_text: "View Website",
    state_image_url: "",
    state_image_position: "",
    location_image_url: "",
  },
  state_specific: {
    HI: {
      name: "Hawaii",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    AK: {
      name: "Alaska",
      hover_color: "#d4aae7",
      color: "#b167d3",
      zoomable: "no",
      inactive: "yes",
    },
    FL: {
      name: "Florida",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NH: {
      name: "New Hampshire",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    VT: {
      name: "Vermont",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    ME: {
      name: "Maine",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    RI: {
      name: "Rhode Island",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NY: {
      name: "New York",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    PA: {
      name: "Pennsylvania",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NJ: {
      name: "New Jersey",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    DE: {
      name: "Delaware",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MD: {
      name: "Maryland",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    VA: {
      name: "Virginia",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    WV: {
      name: "West Virginia",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    OH: {
      name: "Ohio",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    IN: {
      name: "Indiana",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    IL: {
      name: "Illinois",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    CT: {
      name: "Connecticut",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    WI: {
      name: "Wisconsin",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NC: {
      name: "North Carolina",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    DC: {
      name: "District of Columbia",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MA: {
      name: "Massachusetts",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    TN: {
      name: "Tennessee",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    AR: {
      name: "Arkansas",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MO: {
      name: "Missouri",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    GA: {
      name: "Georgia",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    SC: {
      name: "South Carolina",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    KY: {
      name: "Kentucky",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    AL: {
      name: "Alabama",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    LA: {
      name: "Louisiana",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MS: {
      name: "Mississippi",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    IA: {
      name: "Iowa",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MN: {
      name: "Minnesota",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    OK: {
      name: "Oklahoma",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    TX: {
      name: "Texas",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NM: {
      name: "New Mexico",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    KS: {
      name: "Kansas",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NE: {
      name: "Nebraska",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    SD: {
      name: "South Dakota",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    ND: {
      name: "North Dakota",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    WY: {
      name: "Wyoming",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MT: {
      name: "Montana",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    CO: {
      name: "Colorado",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    UT: {
      name: "Utah",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    AZ: {
      name: "Arizona",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    NV: {
      name: "Nevada",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    OR: {
      name: "Oregon",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    WA: {
      name: "Washington",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    CA: {
      name: "California",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    MI: {
      name: "Michigan",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    ID: {
      name: "Idaho",
      color: "#b167d3",
      hover_color: "#d4aae7",
      zoomable: "no",
      inactive: "yes",
    },
    GU: {
      name: "Guam",
      hide: "yes",
      color: "#b167d3",
      hover_color: "#d4aae7",
      inactive: "yes",
      zoomable: "no",
    },
    VI: {
      name: "Virgin Islands",
      hide: "yes",
      color: "#b167d3",
      hover_color: "#d4aae7",
      inactive: "yes",
      zoomable: "no",
    },
    PR: {
      name: "Puerto Rico",
      hide: "yes",
      color: "#b167d3",
      hover_color: "#d4aae7",
      inactive: "yes",
      zoomable: "no",
    },
    MP: {
      name: "Northern Mariana Islands",
      hide: "yes",
      color: "#b167d3",
      hover_color: "#d4aae7",
      inactive: "yes",
      zoomable: "no",
    },
    AS: {
      name: "American Samoa",
      hide: "yes",
      color: "#b167d3",
      hover_color: "#d4aae7",
      inactive: "yes",
      zoomable: "no",
    },
    averi_thompson: {
      name: "Averi Thompson",
      states: [
        "NC",
        "ME",
        "RI",
        "NH",
        "VT",
        "NJ",
        "PA",
        "WV",
        "MT",
        "OR",
        "WA",
        "AK",
      ],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Averi Thompson",
      url: "javascript:showCalendarSlide(0)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/averi_thompson_territory.geojson",
      assignee: "Averi Thompson",
      assignee_email: "averi.thompson@parachutehealth.com",
      assignee_hub_id: "1550980942",
      slide_index: 0,
    },
    blake_townsend: {
      name: "Blake Townsend",
      states: ["NY", "MA", "CT"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Blake Townsend",
      url: "javascript:showCalendarSlide(1)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/blake_townsend_territory.geojson",
      assignee: "Blake Townsend",
      assignee_email: "blake.townsend@parachutehealth.com",
      assignee_hub_id: "1767554280",
      slide_index: 1,
    },
    bethany_visser: {
      name: "Bethany Visser",
      states: ["AL", "MS", "IA", "ND", "SD", "MO", "LA", "AR", "NV"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Bethany Visser",
      url: "javascript:showCalendarSlide(2)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/bethany_visser_territory.geojson",
      assignee: "Bethany Visser",
      assignee_email: "bethany.visser@parachutehealth.com",
      assignee_hub_id: "260195125",
      slide_index: 2,
    },
    john_ciaccio: {
      name: "John Ciaccio",
      states: ["KY", "TN"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "John Ciaccio",
      url: "javascript:showCalendarSlide(3)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/john_ciaccio_territory.geojson",
      assignee: "John Ciaccio",
      assignee_email: "john.ciaccio@parachutehealth.com",
      assignee_hub_id: "82600121",
      slide_index: 3,
    },
    gary_mosley: {
      name: "Gary Mosley",
      states: ["SC", "GA"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Gary Mosley",
      url: "javascript:showCalendarSlide(4)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/gary_mosley_territory.geojson",
      assignee: "Gary Mosley",
      assignee_email: "gary.mosley@parachutehealth.com",
      assignee_hub_id: "551647021",
      slide_index: 4,
    },
    eddy_roth: {
      name: "Eddy Roth",
      states: ["MD", "DE", "DC", "VA"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Eddy Roth",
      url: "javascript:showCalendarSlide(5)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/eddy_roth_territory.geojson",
      assignee: "Eddy Roth",
      assignee_email: "eddy.roth@parachutehealth.com",
      assignee_hub_id: "82992748",
      slide_index: 5,
    },
    ben_reeve: {
      name: "Ben Reeve",
      states: ["MN", "WI", "IL"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Ben Reeve",
      url: "javascript:showCalendarSlide(6)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/ben_reeve_territory.geojson",
      assignee: "Ben Reeve",
      assignee_email: "ben.reeve@parachutehealth.com",
      assignee_hub_id: "82991473",
      slide_index: 6,
    },
    saskia_ottley: {
      name: "Saskia Ottley",
      states: ["FL"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Saskia Ottley",
      url: "javascript:showCalendarSlide(7)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/saskia_ottley_territory.geojson",
      assignee: "Saskia Ottley",
      assignee_email: "saskia.ottley@parachutehealth.com",
      assignee_hub_id: "404006513",
      slide_index: 7,
    },
    hayden_hoffman: {
      name: "Hayden Hoffman",
      states: ["OH", "IN", "MI"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Hayden Hoffman",
      url: "javascript:showCalendarSlide(8)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/hayden_hoffman_territory.geojson",
      assignee: "Hayden Hoffman",
      assignee_email: "hayden.hoffman@parachutehealth.com",
      assignee_hub_id: "82992781",
      slide_index: 8,
    },
    halee_escamilla: {
      name: "Halee Escamilla",
      states: ["OK", "TX"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Halee Escamilla",
      url: "javascript:showCalendarSlide(9)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/halee_escamilla_territory.geojson",
      assignee: "Halee Escamilla",
      assignee_email: "halee.escamilla@parachutehealth.com",
      assignee_hub_id: "82600150",
      slide_index: 9,
    },
    greg_weyl: {
      name: "Greg Weyl",
      states: ["CO", "KS", "NE"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Greg Weyl",
      url: "javascript:showCalendarSlide(10)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/greg_weyl_territory.geojson",
      assignee: "Greg Weyl",
      assignee_email: "greg.weyl@parachutehealth.com",
      assignee_hub_id: "79963359",
      slide_index: 10,
    },
    jordain_buckland: {
      name: "Jordain Buckland",
      states: ["CA", "AZ", "HI"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Jordain Buckland",
      url: "javascript:showCalendarSlide(11)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/jordain_buckland_territory.geojson",
      assignee: "Jordain Buckland",
      assignee_email: "jordain.buckland@parachutehealth.com",
      assignee_hub_id: "79114374",
      slide_index: 11,
    },
    brian_osorio: {
      name: "Brian Osorio",
      states: ["WY", "ID", "UT"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Brian Osorio",
      url: "javascript:showCalendarSlide(12)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/brian_osorio_territory.geojson",
      assignee: "Brian Osorio",
      assignee_email: "brian.osorio@parachutehealth.com",
      assignee_hub_id: "82991503",
      slide_index: 12,
    },
    james_sullivan: {
      name: "James Sullivan",
      states: ["TX", "NM"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "James Sullivan",
      url: "javascript:showCalendarSlide(13)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/james_sullivan_territory.geojson",
      assignee: "James Sullivan",
      assignee_email: "james.sullivan@parachutehealth.com",
      assignee_hub_id: "82600141",
      slide_index: 13,
    },
    "": {
      name: "{}",
      states: ["GU"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "{}",
      url: "javascript:showCalendarSlide(14)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/_territory.geojson",
      assignee: "{}",
      assignee_email: "{}",
      assignee_hub_id: "{}",
      slide_index: 14,
    },
  },
  locations: {
    /*
    0: {
      name: "Virginia Beach, VA",
      lat: "36.859618",
      lng: "-76.036212",
      opacity: "1",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Averi Thompson",
    },
    1: {
      name: "Pensacola, FL",
      lat: "30.446540",
      lng: "-87.207598",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Bethany Visser",
    },
    2: {
      name: "New York, NY",
      lat: "40.763258",
      lng: "-73.980913",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Blake Townsend",
    },
    3: {
      name: "Denver, CO",
      lat: "39.748820",
      lng: "-104.976302",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Greg Weyl",
    },
    4: {
      name: "Phoenix, AZ",
      lat: "33.502031",
      lng: "-112.087773",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Jordain Buckland",
    },
    5: {
      name: "Nashville, TN",
      lat: "36.197745",
      lng: "-86.767169",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "John Ciaccio",
    },
    6: {
      name: "Austin, TX",
      lat: "30.291861",
      lng: "-97.745345",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "James Sullivan",
    },
    7: {
      name: "Dallas, TX",
      lat: "32.791271",
      lng: "-96.779489",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Halee Escamilla",
    },
    8: {
      name: "Miami, FL",
      lat: "25.790737",
      lng: "-80.219904",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Saskia Ottley",
    },
    9: {
      name: "Wisconsin",
      lat: "44.589382",
      lng: "-89.660095",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Ben Reeve",
    },
    10: {
      name: "Ohio",
      lat: "39.896484",
      lng: "-83.013256",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Hayden Hoffman",
    },
    11: {
      name: "Owings Mills, MD",
      lat: "39.419354",
      lng: "-76.791680",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Eddy Roth",
    },
    12: {
      name: "Atlanta, GA",
      lat: "33.734162",
      lng: "-84.399622",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Gary Mosely",
    },
    13: {
      name: "Salt Lake City, UT",
      lat: "40.747157",
      lng: "-111.885242",
      type: "image",
      image_url:
        "https://images.squarespace-cdn.com/content/5df13db27cfbe70b38ae20dd/8d3bb82f-e9e9-4a45-811f-65af120bd25d/Logo-purple-green.png?content-type=image%2Fpng",
      description: "Brian Osorio",
    },
  */
  },
  labels: {
    0: {
      display: "no",
    },
    NH: {
      x: "932",
      y: "183",
      width: 45,
      pill: "yes",
      display: "all",
      parent_id: "NH",
    },
    VT: {
      x: "883",
      y: "243",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "VT",
    },
    RI: {
      x: "932",
      y: "273",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "RI",
    },
    NJ: {
      x: "883",
      y: "273",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "NJ",
    },
    DE: {
      x: "883",
      y: "303",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "DE",
    },
    MD: {
      x: "932",
      y: "303",
      width: 45,
      display: "all",
      scale: "yes",
      pill: "yes",
      parent_id: "MD",
    },
    DC: {
      x: "884",
      y: "332",
      width: 45,
      display: "all",
      scale: "yes",
      pill: "yes",
      parent_id: "DC",
    },
    MA: {
      x: "932",
      y: "213",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "MA",
    },
    CT: {
      x: "932",
      y: "243",
      width: 45,
      display: "all",
      pill: "yes",
      parent_id: "CT",
    },
    HI: {
      x: "305",
      y: "565",
      pill: "yes",
      parent_id: "HI",
    },
    AK: {
      x: "113",
      y: "495",
      display: "no",
      pill: "no",
    },
    FL: {
      x: "773",
      y: "510",
      display: "no",
      pill: "no",
    },
    ME: {
      x: "893",
      y: "85",
      display: "no",
      pill: "no",
    },
    NY: {
      x: "815",
      y: "158",
      display: "no",
      pill: "no",
    },
    PA: {
      x: "786",
      y: "210",
      display: "no",
      pill: "no",
    },
    VA: {
      x: "790",
      y: "282",
      display: "no",
      pill: "no",
    },
    WV: {
      x: "744",
      y: "270",
      display: "no",
      pill: "no",
    },
    OH: {
      x: "700",
      y: "240",
      display: "no",
      pill: "no",
    },
    IN: {
      x: "650",
      y: "250",
      display: "no",
      pill: "no",
    },
    IL: {
      x: "600",
      y: "250",
      display: "no",
      pill: "no",
    },
    WI: {
      x: "575",
      y: "155",
      display: "no",
      pill: "no",
    },
    NC: {
      x: "784",
      y: "326",
      display: "no",
      pill: "no",
    },
    TN: {
      x: "655",
      y: "340",
      display: "no",
      pill: "no",
    },
    AR: {
      x: "548",
      y: "368",
      display: "no",
      pill: "no",
    },
    MO: {
      x: "548",
      y: "293",
      display: "no",
      pill: "no",
    },
    GA: {
      x: "718",
      y: "405",
      display: "no",
      pill: "no",
    },
    SC: {
      x: "760",
      y: "371",
      display: "no",
      pill: "no",
    },
    KY: {
      x: "680",
      y: "300",
      display: "no",
      pill: "no",
    },
    AL: {
      x: "655",
      y: "405",
      display: "no",
      pill: "no",
    },
    LA: {
      x: "550",
      y: "435",
      display: "no",
      pill: "no",
    },
    MS: {
      x: "600",
      y: "405",
      display: "no",
      pill: "no",
    },
    IA: {
      x: "525",
      y: "210",
      display: "no",
      pill: "no",
    },
    MN: {
      x: "506",
      y: "124",
      display: "no",
      pill: "no",
    },
    OK: {
      x: "460",
      y: "360",
      display: "no",
      pill: "no",
    },
    TX: {
      x: "425",
      y: "435",
      display: "no",
      pill: "no",
    },
    NM: {
      x: "305",
      y: "365",
      display: "no",
      pill: "no",
    },
    KS: {
      x: "445",
      y: "290",
      display: "no",
      pill: "no",
    },
    NE: {
      x: "420",
      y: "225",
      display: "no",
      pill: "no",
    },
    SD: {
      x: "413",
      y: "160",
      display: "no",
      pill: "no",
    },
    ND: {
      x: "416",
      y: "96",
      display: "no",
      pill: "no",
    },
    WY: {
      x: "300",
      y: "180",
      display: "no",
      pill: "no",
    },
    MT: {
      x: "280",
      y: "95",
      display: "no",
      pill: "no",
    },
    CO: {
      x: "320",
      y: "275",
      display: "no",
      pill: "no",
    },
    UT: {
      x: "223",
      y: "260",
      display: "no",
      pill: "no",
    },
    AZ: {
      x: "205",
      y: "360",
      display: "no",
      pill: "no",
    },
    NV: {
      x: "140",
      y: "235",
      display: "no",
      pill: "no",
    },
    OR: {
      x: "100",
      y: "120",
      display: "no",
      pill: "no",
    },
    WA: {
      x: "130",
      y: "55",
      display: "no",
      pill: "no",
    },
    ID: {
      x: "200",
      y: "150",
      display: "no",
      pill: "no",
    },
    CA: {
      x: "79",
      y: "285",
      display: "no",
      pill: "no",
    },
    MI: {
      x: "663",
      y: "185",
      display: "no",
      pill: "no",
    },
    PR: {
      x: "620",
      y: "545",
      display: "no",
      pill: "no",
    },
    GU: {
      x: "550",
      y: "540",
      display: "no",
      pill: "no",
    },
    VI: {
      x: "680",
      y: "519",
      display: "no",
      pill: "no",
    },
    MP: {
      x: "570",
      y: "575",
      display: "no",
      pill: "no",
    },
    AS: {
      x: "665",
      y: "580",
      display: "no",
      pill: "no",
    },
  },
  legend: {
    entries: [],
  },
  regions: {
    averi_thompson: {
      name: "Averi Thompson",
      states: [
        "NC",
        "ME",
        "RI",
        "NH",
        "VT",
        "NJ",
        "PA",
        "WV",
        "MT",
        "OR",
        "WA",
        "AK",
      ],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Averi Thompson",
      url: "javascript:showCalendarSlide(0)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/averi_thompson_territory.geojson",
      assignee: "Averi Thompson",
      assignee_email: "averi.thompson@parachutehealth.com",
      assignee_hub_id: "1550980942",
      slide_index: 0,
    },
    blake_townsend: {
      name: "Blake Townsend",
      states: ["NY", "MA", "CT"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Blake Townsend",
      url: "javascript:showCalendarSlide(1)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/blake_townsend_territory.geojson",
      assignee: "Blake Townsend",
      assignee_email: "blake.townsend@parachutehealth.com",
      assignee_hub_id: "1767554280",
      slide_index: 1,
    },
    bethany_visser: {
      name: "Bethany Visser",
      states: ["AL", "MS", "IA", "ND", "SD", "MO", "LA", "AR", "NV"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Bethany Visser",
      url: "javascript:showCalendarSlide(2)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/bethany_visser_territory.geojson",
      assignee: "Bethany Visser",
      assignee_email: "bethany.visser@parachutehealth.com",
      assignee_hub_id: "260195125",
      slide_index: 2,
    },
    john_ciaccio: {
      name: "John Ciaccio",
      states: ["KY", "TN"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "John Ciaccio",
      url: "javascript:showCalendarSlide(3)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/john_ciaccio_territory.geojson",
      assignee: "John Ciaccio",
      assignee_email: "john.ciaccio@parachutehealth.com",
      assignee_hub_id: "82600121",
      slide_index: 3,
    },
    gary_mosley: {
      name: "Gary Mosley",
      states: ["SC", "GA"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Gary Mosley",
      url: "javascript:showCalendarSlide(4)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/gary_mosley_territory.geojson",
      assignee: "Gary Mosley",
      assignee_email: "gary.mosley@parachutehealth.com",
      assignee_hub_id: "551647021",
      slide_index: 4,
    },
    eddy_roth: {
      name: "Eddy Roth",
      states: ["MD", "DE", "DC", "VA"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Eddy Roth",
      url: "javascript:showCalendarSlide(5)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/eddy_roth_territory.geojson",
      assignee: "Eddy Roth",
      assignee_email: "eddy.roth@parachutehealth.com",
      assignee_hub_id: "82992748",
      slide_index: 5,
    },
    ben_reeve: {
      name: "Ben Reeve",
      states: ["MN", "WI", "IL"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Ben Reeve",
      url: "javascript:showCalendarSlide(6)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/ben_reeve_territory.geojson",
      assignee: "Ben Reeve",
      assignee_email: "ben.reeve@parachutehealth.com",
      assignee_hub_id: "82991473",
      slide_index: 6,
    },
    saskia_ottley: {
      name: "Saskia Ottley",
      states: ["FL"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Saskia Ottley",
      url: "javascript:showCalendarSlide(7)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/saskia_ottley_territory.geojson",
      assignee: "Saskia Ottley",
      assignee_email: "saskia.ottley@parachutehealth.com",
      assignee_hub_id: "404006513",
      slide_index: 7,
    },
    hayden_hoffman: {
      name: "Hayden Hoffman",
      states: ["OH", "IN", "MI"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Hayden Hoffman",
      url: "javascript:showCalendarSlide(8)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/hayden_hoffman_territory.geojson",
      assignee: "Hayden Hoffman",
      assignee_email: "hayden.hoffman@parachutehealth.com",
      assignee_hub_id: "82992781",
      slide_index: 8,
    },
    halee_escamilla: {
      name: "Halee Escamilla",
      states: ["OK", "TX"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Halee Escamilla",
      url: "javascript:showCalendarSlide(9)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/halee_escamilla_territory.geojson",
      assignee: "Halee Escamilla",
      assignee_email: "halee.escamilla@parachutehealth.com",
      assignee_hub_id: "82600150",
      slide_index: 9,
    },
    greg_weyl: {
      name: "Greg Weyl",
      states: ["CO", "KS", "NE"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Greg Weyl",
      url: "javascript:showCalendarSlide(10)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/greg_weyl_territory.geojson",
      assignee: "Greg Weyl",
      assignee_email: "greg.weyl@parachutehealth.com",
      assignee_hub_id: "79963359",
      slide_index: 10,
    },
    jordain_buckland: {
      name: "Jordain Buckland",
      states: ["CA", "AZ", "HI"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Jordain Buckland",
      url: "javascript:showCalendarSlide(11)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/jordain_buckland_territory.geojson",
      assignee: "Jordain Buckland",
      assignee_email: "jordain.buckland@parachutehealth.com",
      assignee_hub_id: "79114374",
      slide_index: 11,
    },
    brian_osorio: {
      name: "Brian Osorio",
      states: ["WY", "ID", "UT"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "Brian Osorio",
      url: "javascript:showCalendarSlide(12)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/brian_osorio_territory.geojson",
      assignee: "Brian Osorio",
      assignee_email: "brian.osorio@parachutehealth.com",
      assignee_hub_id: "82991503",
      slide_index: 12,
    },
    james_sullivan: {
      name: "James Sullivan",
      states: ["TX", "NM"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "James Sullivan",
      url: "javascript:showCalendarSlide(13)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/james_sullivan_territory.geojson",
      assignee: "James Sullivan",
      assignee_email: "james.sullivan@parachutehealth.com",
      assignee_hub_id: "82600141",
      slide_index: 13,
    },
    "": {
      name: "{}",
      states: ["GU"],
      color: "#b167d3",
      hover_color: "#d4aae7",
      description: "{}",
      url: "javascript:showCalendarSlide(14)",
      geojson_url:
        "https://raw.githubusercontent.com/sammyatparachute/ph-marketing-site/refs/heads/main/_territory.geojson",
      assignee: "{}",
      assignee_email: "{}",
      assignee_hub_id: "{}",
      slide_index: 14,
    },
  },
};
